// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: browse_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InnerTube.Protobuf.Responses {

  /// <summary>Holder for reflection information generated from browse_response.proto</summary>
  public static partial class BrowseResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for browse_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BrowseResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVicm93c2VfcmVzcG9uc2UucHJvdG8SHElubmVyVHViZS5Qcm90b2J1Zi5S",
            "ZXNwb25zZXMaDWdlbmVyYWwucHJvdG8imgMKDkJyb3dzZVJlc3BvbnNlEjUK",
            "CGNvbnRlbnRzGAkgASgLMiMuSW5uZXJUdWJlLlByb3RvYnVmLlJlbmRlcmVy",
            "V3JhcHBlchI4CgZoZWFkZXIYDSABKAsyIy5Jbm5lclR1YmUuUHJvdG9idWYu",
            "UmVuZGVyZXJXcmFwcGVySACIAQESMwoGYWxlcnRzGA4gAygLMiMuSW5uZXJU",
            "dWJlLlByb3RvYnVmLlJlbmRlcmVyV3JhcHBlchI6CghtZXRhZGF0YRgPIAEo",
            "CzIjLklubmVyVHViZS5Qcm90b2J1Zi5SZW5kZXJlcldyYXBwZXJIAYgBARI9",
            "CgttaWNyb2Zvcm1hdBgbIAEoCzIjLklubmVyVHViZS5Qcm90b2J1Zi5SZW5k",
            "ZXJlcldyYXBwZXJIAogBARI/ChlvblJlc3BvbnNlUmVjZWl2ZWRBY3Rpb25z",
            "GB4gASgLMhwuSW5uZXJUdWJlLlByb3RvYnVmLkVuZHBvaW50QgkKB19oZWFk",
            "ZXJCCwoJX21ldGFkYXRhQg4KDF9taWNyb2Zvcm1hdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::InnerTube.Protobuf.GeneralReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Responses.BrowseResponse), global::InnerTube.Protobuf.Responses.BrowseResponse.Parser, new[]{ "Contents", "Header", "Alerts", "Metadata", "Microformat", "OnResponseReceivedActions" }, new[]{ "Header", "Metadata", "Microformat" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BrowseResponse : pb::IMessage<BrowseResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BrowseResponse> _parser = new pb::MessageParser<BrowseResponse>(() => new BrowseResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BrowseResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Responses.BrowseResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseResponse(BrowseResponse other) : this() {
      contents_ = other.contents_ != null ? other.contents_.Clone() : null;
      header_ = other.header_ != null ? other.header_.Clone() : null;
      alerts_ = other.alerts_.Clone();
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      microformat_ = other.microformat_ != null ? other.microformat_.Clone() : null;
      onResponseReceivedActions_ = other.onResponseReceivedActions_ != null ? other.onResponseReceivedActions_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseResponse Clone() {
      return new BrowseResponse(this);
    }

    /// <summary>Field number for the "contents" field.</summary>
    public const int ContentsFieldNumber = 9;
    private global::InnerTube.Protobuf.RendererWrapper contents_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.RendererWrapper Contents {
      get { return contents_; }
      set {
        contents_ = value;
      }
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 13;
    private global::InnerTube.Protobuf.RendererWrapper header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.RendererWrapper Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "alerts" field.</summary>
    public const int AlertsFieldNumber = 14;
    private static readonly pb::FieldCodec<global::InnerTube.Protobuf.RendererWrapper> _repeated_alerts_codec
        = pb::FieldCodec.ForMessage(114, global::InnerTube.Protobuf.RendererWrapper.Parser);
    private readonly pbc::RepeatedField<global::InnerTube.Protobuf.RendererWrapper> alerts_ = new pbc::RepeatedField<global::InnerTube.Protobuf.RendererWrapper>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::InnerTube.Protobuf.RendererWrapper> Alerts {
      get { return alerts_; }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 15;
    private global::InnerTube.Protobuf.RendererWrapper metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.RendererWrapper Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "microformat" field.</summary>
    public const int MicroformatFieldNumber = 27;
    private global::InnerTube.Protobuf.RendererWrapper microformat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.RendererWrapper Microformat {
      get { return microformat_; }
      set {
        microformat_ = value;
      }
    }

    /// <summary>Field number for the "onResponseReceivedActions" field.</summary>
    public const int OnResponseReceivedActionsFieldNumber = 30;
    private global::InnerTube.Protobuf.Endpoint onResponseReceivedActions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Endpoint OnResponseReceivedActions {
      get { return onResponseReceivedActions_; }
      set {
        onResponseReceivedActions_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BrowseResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BrowseResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Contents, other.Contents)) return false;
      if (!object.Equals(Header, other.Header)) return false;
      if(!alerts_.Equals(other.alerts_)) return false;
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(Microformat, other.Microformat)) return false;
      if (!object.Equals(OnResponseReceivedActions, other.OnResponseReceivedActions)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (contents_ != null) hash ^= Contents.GetHashCode();
      if (header_ != null) hash ^= Header.GetHashCode();
      hash ^= alerts_.GetHashCode();
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (microformat_ != null) hash ^= Microformat.GetHashCode();
      if (onResponseReceivedActions_ != null) hash ^= OnResponseReceivedActions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (contents_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Contents);
      }
      if (header_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Header);
      }
      alerts_.WriteTo(output, _repeated_alerts_codec);
      if (metadata_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Metadata);
      }
      if (microformat_ != null) {
        output.WriteRawTag(218, 1);
        output.WriteMessage(Microformat);
      }
      if (onResponseReceivedActions_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(OnResponseReceivedActions);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (contents_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Contents);
      }
      if (header_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Header);
      }
      alerts_.WriteTo(ref output, _repeated_alerts_codec);
      if (metadata_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Metadata);
      }
      if (microformat_ != null) {
        output.WriteRawTag(218, 1);
        output.WriteMessage(Microformat);
      }
      if (onResponseReceivedActions_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(OnResponseReceivedActions);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (contents_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contents);
      }
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      size += alerts_.CalculateSize(_repeated_alerts_codec);
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (microformat_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Microformat);
      }
      if (onResponseReceivedActions_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OnResponseReceivedActions);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BrowseResponse other) {
      if (other == null) {
        return;
      }
      if (other.contents_ != null) {
        if (contents_ == null) {
          Contents = new global::InnerTube.Protobuf.RendererWrapper();
        }
        Contents.MergeFrom(other.Contents);
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::InnerTube.Protobuf.RendererWrapper();
        }
        Header.MergeFrom(other.Header);
      }
      alerts_.Add(other.alerts_);
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::InnerTube.Protobuf.RendererWrapper();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.microformat_ != null) {
        if (microformat_ == null) {
          Microformat = new global::InnerTube.Protobuf.RendererWrapper();
        }
        Microformat.MergeFrom(other.Microformat);
      }
      if (other.onResponseReceivedActions_ != null) {
        if (onResponseReceivedActions_ == null) {
          OnResponseReceivedActions = new global::InnerTube.Protobuf.Endpoint();
        }
        OnResponseReceivedActions.MergeFrom(other.OnResponseReceivedActions);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 74: {
            if (contents_ == null) {
              Contents = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Contents);
            break;
          }
          case 106: {
            if (header_ == null) {
              Header = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Header);
            break;
          }
          case 114: {
            alerts_.AddEntriesFrom(input, _repeated_alerts_codec);
            break;
          }
          case 122: {
            if (metadata_ == null) {
              Metadata = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 218: {
            if (microformat_ == null) {
              Microformat = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Microformat);
            break;
          }
          case 242: {
            if (onResponseReceivedActions_ == null) {
              OnResponseReceivedActions = new global::InnerTube.Protobuf.Endpoint();
            }
            input.ReadMessage(OnResponseReceivedActions);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 74: {
            if (contents_ == null) {
              Contents = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Contents);
            break;
          }
          case 106: {
            if (header_ == null) {
              Header = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Header);
            break;
          }
          case 114: {
            alerts_.AddEntriesFrom(ref input, _repeated_alerts_codec);
            break;
          }
          case 122: {
            if (metadata_ == null) {
              Metadata = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 218: {
            if (microformat_ == null) {
              Microformat = new global::InnerTube.Protobuf.RendererWrapper();
            }
            input.ReadMessage(Microformat);
            break;
          }
          case 242: {
            if (onResponseReceivedActions_ == null) {
              OnResponseReceivedActions = new global::InnerTube.Protobuf.Endpoint();
            }
            input.ReadMessage(OnResponseReceivedActions);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
