// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: endpoints.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InnerTube.Protobuf.Endpoints {

  /// <summary>Holder for reflection information generated from endpoints.proto</summary>
  public static partial class EndpointsReflection {

    #region Descriptor
    /// <summary>File descriptor for endpoints.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EndpointsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9lbmRwb2ludHMucHJvdG8SHElubmVyVHViZS5Qcm90b2J1Zi5FbmRwb2lu",
            "dHMi8wEKCEVuZHBvaW50EkcKDXdhdGNoRW5kcG9pbnQYjdWbFyABKAsyKy5J",
            "bm5lclR1YmUuUHJvdG9idWYuRW5kcG9pbnRzLldhdGNoRW5kcG9pbnRIABJD",
            "Cgt1cmxFbmRwb2ludBiVl9gXIAEoCzIpLklubmVyVHViZS5Qcm90b2J1Zi5F",
            "bmRwb2ludHMuVXJsRW5kcG9pbnRIABJJCg5icm93c2VFbmRwb2ludBiK1JsX",
            "IAEoCzIsLklubmVyVHViZS5Qcm90b2J1Zi5FbmRwb2ludHMuQnJvd3NlRW5k",
            "cG9pbnRIAEIOCgxlbmRwb2ludFR5cGUiSAoNV2F0Y2hFbmRwb2ludBIPCgd2",
            "aWRlb0lkGAEgASgJEhcKCnBsYXlsaXN0SWQYAiABKAlIAIgBAUINCgtfcGxh",
            "eWxpc3RJZCIqCgtVcmxFbmRwb2ludBILCgN1cmwYASABKAkSDgoGdGFyZ2V0",
            "GAIgASgFIiIKDkJyb3dzZUVuZHBvaW50EhAKCGJyb3dzZUlkGAIgASgJYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Endpoints.Endpoint), global::InnerTube.Protobuf.Endpoints.Endpoint.Parser, new[]{ "WatchEndpoint", "UrlEndpoint", "BrowseEndpoint" }, new[]{ "EndpointType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Endpoints.WatchEndpoint), global::InnerTube.Protobuf.Endpoints.WatchEndpoint.Parser, new[]{ "VideoId", "PlaylistId" }, new[]{ "PlaylistId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Endpoints.UrlEndpoint), global::InnerTube.Protobuf.Endpoints.UrlEndpoint.Parser, new[]{ "Url", "Target" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Endpoints.BrowseEndpoint), global::InnerTube.Protobuf.Endpoints.BrowseEndpoint.Parser, new[]{ "BrowseId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Endpoint : pb::IMessage<Endpoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Endpoint> _parser = new pb::MessageParser<Endpoint>(() => new Endpoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Endpoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Endpoints.EndpointsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint(Endpoint other) : this() {
      switch (other.EndpointTypeCase) {
        case EndpointTypeOneofCase.WatchEndpoint:
          WatchEndpoint = other.WatchEndpoint.Clone();
          break;
        case EndpointTypeOneofCase.UrlEndpoint:
          UrlEndpoint = other.UrlEndpoint.Clone();
          break;
        case EndpointTypeOneofCase.BrowseEndpoint:
          BrowseEndpoint = other.BrowseEndpoint.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint Clone() {
      return new Endpoint(this);
    }

    /// <summary>Field number for the "watchEndpoint" field.</summary>
    public const int WatchEndpointFieldNumber = 48687757;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Endpoints.WatchEndpoint WatchEndpoint {
      get { return endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint ? (global::InnerTube.Protobuf.Endpoints.WatchEndpoint) endpointType_ : null; }
      set {
        endpointType_ = value;
        endpointTypeCase_ = value == null ? EndpointTypeOneofCase.None : EndpointTypeOneofCase.WatchEndpoint;
      }
    }

    /// <summary>Field number for the "urlEndpoint" field.</summary>
    public const int UrlEndpointFieldNumber = 49679253;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Endpoints.UrlEndpoint UrlEndpoint {
      get { return endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint ? (global::InnerTube.Protobuf.Endpoints.UrlEndpoint) endpointType_ : null; }
      set {
        endpointType_ = value;
        endpointTypeCase_ = value == null ? EndpointTypeOneofCase.None : EndpointTypeOneofCase.UrlEndpoint;
      }
    }

    /// <summary>Field number for the "browseEndpoint" field.</summary>
    public const int BrowseEndpointFieldNumber = 48687626;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Endpoints.BrowseEndpoint BrowseEndpoint {
      get { return endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint ? (global::InnerTube.Protobuf.Endpoints.BrowseEndpoint) endpointType_ : null; }
      set {
        endpointType_ = value;
        endpointTypeCase_ = value == null ? EndpointTypeOneofCase.None : EndpointTypeOneofCase.BrowseEndpoint;
      }
    }

    private object endpointType_;
    /// <summary>Enum of possible cases for the "endpointType" oneof.</summary>
    public enum EndpointTypeOneofCase {
      None = 0,
      WatchEndpoint = 48687757,
      UrlEndpoint = 49679253,
      BrowseEndpoint = 48687626,
    }
    private EndpointTypeOneofCase endpointTypeCase_ = EndpointTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndpointTypeOneofCase EndpointTypeCase {
      get { return endpointTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEndpointType() {
      endpointTypeCase_ = EndpointTypeOneofCase.None;
      endpointType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Endpoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Endpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(WatchEndpoint, other.WatchEndpoint)) return false;
      if (!object.Equals(UrlEndpoint, other.UrlEndpoint)) return false;
      if (!object.Equals(BrowseEndpoint, other.BrowseEndpoint)) return false;
      if (EndpointTypeCase != other.EndpointTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) hash ^= WatchEndpoint.GetHashCode();
      if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) hash ^= UrlEndpoint.GetHashCode();
      if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) hash ^= BrowseEndpoint.GetHashCode();
      hash ^= (int) endpointTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) {
        output.WriteRawTag(210, 160, 221, 185, 1);
        output.WriteMessage(BrowseEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) {
        output.WriteRawTag(234, 168, 221, 185, 1);
        output.WriteMessage(WatchEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) {
        output.WriteRawTag(170, 185, 193, 189, 1);
        output.WriteMessage(UrlEndpoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) {
        output.WriteRawTag(210, 160, 221, 185, 1);
        output.WriteMessage(BrowseEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) {
        output.WriteRawTag(234, 168, 221, 185, 1);
        output.WriteMessage(WatchEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) {
        output.WriteRawTag(170, 185, 193, 189, 1);
        output.WriteMessage(UrlEndpoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) {
        size += 5 + pb::CodedOutputStream.ComputeMessageSize(WatchEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) {
        size += 5 + pb::CodedOutputStream.ComputeMessageSize(UrlEndpoint);
      }
      if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) {
        size += 5 + pb::CodedOutputStream.ComputeMessageSize(BrowseEndpoint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Endpoint other) {
      if (other == null) {
        return;
      }
      switch (other.EndpointTypeCase) {
        case EndpointTypeOneofCase.WatchEndpoint:
          if (WatchEndpoint == null) {
            WatchEndpoint = new global::InnerTube.Protobuf.Endpoints.WatchEndpoint();
          }
          WatchEndpoint.MergeFrom(other.WatchEndpoint);
          break;
        case EndpointTypeOneofCase.UrlEndpoint:
          if (UrlEndpoint == null) {
            UrlEndpoint = new global::InnerTube.Protobuf.Endpoints.UrlEndpoint();
          }
          UrlEndpoint.MergeFrom(other.UrlEndpoint);
          break;
        case EndpointTypeOneofCase.BrowseEndpoint:
          if (BrowseEndpoint == null) {
            BrowseEndpoint = new global::InnerTube.Protobuf.Endpoints.BrowseEndpoint();
          }
          BrowseEndpoint.MergeFrom(other.BrowseEndpoint);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 389501010: {
            global::InnerTube.Protobuf.Endpoints.BrowseEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.BrowseEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) {
              subBuilder.MergeFrom(BrowseEndpoint);
            }
            input.ReadMessage(subBuilder);
            BrowseEndpoint = subBuilder;
            break;
          }
          case 389502058: {
            global::InnerTube.Protobuf.Endpoints.WatchEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.WatchEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) {
              subBuilder.MergeFrom(WatchEndpoint);
            }
            input.ReadMessage(subBuilder);
            WatchEndpoint = subBuilder;
            break;
          }
          case 397434026: {
            global::InnerTube.Protobuf.Endpoints.UrlEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.UrlEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) {
              subBuilder.MergeFrom(UrlEndpoint);
            }
            input.ReadMessage(subBuilder);
            UrlEndpoint = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 389501010: {
            global::InnerTube.Protobuf.Endpoints.BrowseEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.BrowseEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.BrowseEndpoint) {
              subBuilder.MergeFrom(BrowseEndpoint);
            }
            input.ReadMessage(subBuilder);
            BrowseEndpoint = subBuilder;
            break;
          }
          case 389502058: {
            global::InnerTube.Protobuf.Endpoints.WatchEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.WatchEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.WatchEndpoint) {
              subBuilder.MergeFrom(WatchEndpoint);
            }
            input.ReadMessage(subBuilder);
            WatchEndpoint = subBuilder;
            break;
          }
          case 397434026: {
            global::InnerTube.Protobuf.Endpoints.UrlEndpoint subBuilder = new global::InnerTube.Protobuf.Endpoints.UrlEndpoint();
            if (endpointTypeCase_ == EndpointTypeOneofCase.UrlEndpoint) {
              subBuilder.MergeFrom(UrlEndpoint);
            }
            input.ReadMessage(subBuilder);
            UrlEndpoint = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchEndpoint : pb::IMessage<WatchEndpoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchEndpoint> _parser = new pb::MessageParser<WatchEndpoint>(() => new WatchEndpoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchEndpoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Endpoints.EndpointsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchEndpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchEndpoint(WatchEndpoint other) : this() {
      videoId_ = other.videoId_;
      playlistId_ = other.playlistId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchEndpoint Clone() {
      return new WatchEndpoint(this);
    }

    /// <summary>Field number for the "videoId" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private string videoId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VideoId {
      get { return videoId_; }
      set {
        videoId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playlistId" field.</summary>
    public const int PlaylistIdFieldNumber = 2;
    private readonly static string PlaylistIdDefaultValue = "";

    private string playlistId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlaylistId {
      get { return playlistId_ ?? PlaylistIdDefaultValue; }
      set {
        playlistId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "playlistId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlaylistId {
      get { return playlistId_ != null; }
    }
    /// <summary>Clears the value of the "playlistId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlaylistId() {
      playlistId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchEndpoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchEndpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoId != other.VideoId) return false;
      if (PlaylistId != other.PlaylistId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VideoId.Length != 0) hash ^= VideoId.GetHashCode();
      if (HasPlaylistId) hash ^= PlaylistId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VideoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VideoId);
      }
      if (HasPlaylistId) {
        output.WriteRawTag(18);
        output.WriteString(PlaylistId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VideoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VideoId);
      }
      if (HasPlaylistId) {
        output.WriteRawTag(18);
        output.WriteString(PlaylistId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VideoId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VideoId);
      }
      if (HasPlaylistId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlaylistId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchEndpoint other) {
      if (other == null) {
        return;
      }
      if (other.VideoId.Length != 0) {
        VideoId = other.VideoId;
      }
      if (other.HasPlaylistId) {
        PlaylistId = other.PlaylistId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VideoId = input.ReadString();
            break;
          }
          case 18: {
            PlaylistId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VideoId = input.ReadString();
            break;
          }
          case 18: {
            PlaylistId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UrlEndpoint : pb::IMessage<UrlEndpoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UrlEndpoint> _parser = new pb::MessageParser<UrlEndpoint>(() => new UrlEndpoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UrlEndpoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Endpoints.EndpointsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UrlEndpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UrlEndpoint(UrlEndpoint other) : this() {
      url_ = other.url_;
      target_ = other.target_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UrlEndpoint Clone() {
      return new UrlEndpoint(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 2;
    private int target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UrlEndpoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UrlEndpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (Target != other.Target) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Target != 0) hash ^= Target.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Target != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Target);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Target != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Target);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Target != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Target);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UrlEndpoint other) {
      if (other == null) {
        return;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Target != 0) {
        Target = other.Target;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Target = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Target = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BrowseEndpoint : pb::IMessage<BrowseEndpoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BrowseEndpoint> _parser = new pb::MessageParser<BrowseEndpoint>(() => new BrowseEndpoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BrowseEndpoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Endpoints.EndpointsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseEndpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseEndpoint(BrowseEndpoint other) : this() {
      browseId_ = other.browseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrowseEndpoint Clone() {
      return new BrowseEndpoint(this);
    }

    /// <summary>Field number for the "browseId" field.</summary>
    public const int BrowseIdFieldNumber = 2;
    private string browseId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BrowseId {
      get { return browseId_; }
      set {
        browseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BrowseEndpoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BrowseEndpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BrowseId != other.BrowseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BrowseId.Length != 0) hash ^= BrowseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BrowseId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BrowseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BrowseId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BrowseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BrowseId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrowseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BrowseEndpoint other) {
      if (other == null) {
        return;
      }
      if (other.BrowseId.Length != 0) {
        BrowseId = other.BrowseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            BrowseId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            BrowseId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
