// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: general.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InnerTube.Protobuf {

  /// <summary>Holder for reflection information generated from general.proto</summary>
  public static partial class GeneralReflection {

    #region Descriptor
    /// <summary>File descriptor for general.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneralReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1nZW5lcmFsLnByb3RvEhJJbm5lclR1YmUuUHJvdG9idWYi+gMKClRodW1i",
            "bmFpbHMSMQoKdGh1bWJuYWlscxgBIAMoCzIdLklubmVyVHViZS5Qcm90b2J1",
            "Zi5UaHVtYm5haWwSRAoNYWNjZXNzaWJpbGl0eRgEIAEoCzIoLklubmVyVHVi",
            "ZS5Qcm90b2J1Zi5BY2Nlc3NpYmlsaXR5V3JhcHBlckgAiAEBEj0KFXNhbXBs",
            "ZWRUaHVtYm5haWxDb2xvchgMIAEoCzIZLklubmVyVHViZS5Qcm90b2J1Zi5D",
            "b2xvckgBiAEBEkAKEWxpZ2h0Q29sb3JQYWxldHRlGA0gASgLMiAuSW5uZXJU",
            "dWJlLlByb3RvYnVmLkNvbG9yUGFsZXR0ZUgCiAEBEj8KEGRhcmtDb2xvclBh",
            "bGV0dGUYDiABKAsyIC5Jbm5lclR1YmUuUHJvdG9idWYuQ29sb3JQYWxldHRl",
            "SAOIAQESQgoTdmlicmFudENvbG9yUGFsZXR0ZRgSIAEoCzIgLklubmVyVHVi",
            "ZS5Qcm90b2J1Zi5Db2xvclBhbGV0dGVIBIgBAUIQCg5fYWNjZXNzaWJpbGl0",
            "eUIYChZfc2FtcGxlZFRodW1ibmFpbENvbG9yQhQKEl9saWdodENvbG9yUGFs",
            "ZXR0ZUITChFfZGFya0NvbG9yUGFsZXR0ZUIWChRfdmlicmFudENvbG9yUGFs",
            "ZXR0ZSI3CglUaHVtYm5haWwSCwoDdXJsGAEgASgJEg0KBXdpZHRoGAIgASgF",
            "Eg4KBmhlaWdodBgDIAEoBSIxCgVDb2xvchILCgNyZWQYASABKAUSDQoFZ3Jl",
            "ZW4YAiABKAUSDAoEYmx1ZRgDIAEoBSIYCgRJY29uEhAKCGljb25UeXBlGAEg",
            "ASgFIiIKEUFjY2Vzc2liaWxpdHlEYXRhEg0KBWxhYmVsGAIgASgJIlsKFEFj",
            "Y2Vzc2liaWxpdHlXcmFwcGVyEkMKEWFjY2Vzc2liaWxpdHlEYXRhGPqZjiQg",
            "ASgLMiUuSW5uZXJUdWJlLlByb3RvYnVmLkFjY2Vzc2liaWxpdHlEYXRhIqID",
            "CgxDb2xvclBhbGV0dGUSGgoNc2VjdGlvbjFDb2xvchgBIAEoA0gAiAEBEhoK",
            "DXNlY3Rpb24yQ29sb3IYAiABKANIAYgBARIaCg1zZWN0aW9uM0NvbG9yGAMg",
            "ASgDSAKIAQESHgoRcHJpbWFyeVRpdGxlQ29sb3IYBSABKANIA4gBARIgChNz",
            "ZWNvbmRhcnlUaXRsZUNvbG9yGAYgASgDSASIAQESHgoRaWNvbkluYWN0aXZl",
            "Q29sb3IYCSABKANIBYgBARIaCg1zZWN0aW9uNENvbG9yGAogASgDSAaIAQES",
            "HgoRaWNvbkRpc2FibGVkQ29sb3IYDCABKANIB4gBAUIQCg5fc2VjdGlvbjFD",
            "b2xvckIQCg5fc2VjdGlvbjJDb2xvckIQCg5fc2VjdGlvbjNDb2xvckIUChJf",
            "cHJpbWFyeVRpdGxlQ29sb3JCFgoUX3NlY29uZGFyeVRpdGxlQ29sb3JCFAoS",
            "X2ljb25JbmFjdGl2ZUNvbG9yQhAKDl9zZWN0aW9uNENvbG9yQhQKEl9pY29u",
            "RGlzYWJsZWRDb2xvcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Thumbnails), global::InnerTube.Protobuf.Thumbnails.Parser, new[]{ "Thumbnails_", "Accessibility", "SampledThumbnailColor", "LightColorPalette", "DarkColorPalette", "VibrantColorPalette" }, new[]{ "Accessibility", "SampledThumbnailColor", "LightColorPalette", "DarkColorPalette", "VibrantColorPalette" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Thumbnail), global::InnerTube.Protobuf.Thumbnail.Parser, new[]{ "Url", "Width", "Height" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Color), global::InnerTube.Protobuf.Color.Parser, new[]{ "Red", "Green", "Blue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Icon), global::InnerTube.Protobuf.Icon.Parser, new[]{ "IconType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.AccessibilityData), global::InnerTube.Protobuf.AccessibilityData.Parser, new[]{ "Label" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.AccessibilityWrapper), global::InnerTube.Protobuf.AccessibilityWrapper.Parser, new[]{ "AccessibilityData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.ColorPalette), global::InnerTube.Protobuf.ColorPalette.Parser, new[]{ "Section1Color", "Section2Color", "Section3Color", "PrimaryTitleColor", "SecondaryTitleColor", "IconInactiveColor", "Section4Color", "IconDisabledColor" }, new[]{ "Section1Color", "Section2Color", "Section3Color", "PrimaryTitleColor", "SecondaryTitleColor", "IconInactiveColor", "Section4Color", "IconDisabledColor" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Thumbnails : pb::IMessage<Thumbnails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Thumbnails> _parser = new pb::MessageParser<Thumbnails>(() => new Thumbnails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Thumbnails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails(Thumbnails other) : this() {
      thumbnails_ = other.thumbnails_.Clone();
      accessibility_ = other.accessibility_ != null ? other.accessibility_.Clone() : null;
      sampledThumbnailColor_ = other.sampledThumbnailColor_ != null ? other.sampledThumbnailColor_.Clone() : null;
      lightColorPalette_ = other.lightColorPalette_ != null ? other.lightColorPalette_.Clone() : null;
      darkColorPalette_ = other.darkColorPalette_ != null ? other.darkColorPalette_.Clone() : null;
      vibrantColorPalette_ = other.vibrantColorPalette_ != null ? other.vibrantColorPalette_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails Clone() {
      return new Thumbnails(this);
    }

    /// <summary>Field number for the "thumbnails" field.</summary>
    public const int Thumbnails_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::InnerTube.Protobuf.Thumbnail> _repeated_thumbnails_codec
        = pb::FieldCodec.ForMessage(10, global::InnerTube.Protobuf.Thumbnail.Parser);
    private readonly pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail> thumbnails_ = new pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail> Thumbnails_ {
      get { return thumbnails_; }
    }

    /// <summary>Field number for the "accessibility" field.</summary>
    public const int AccessibilityFieldNumber = 4;
    private global::InnerTube.Protobuf.AccessibilityWrapper accessibility_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.AccessibilityWrapper Accessibility {
      get { return accessibility_; }
      set {
        accessibility_ = value;
      }
    }

    /// <summary>Field number for the "sampledThumbnailColor" field.</summary>
    public const int SampledThumbnailColorFieldNumber = 12;
    private global::InnerTube.Protobuf.Color sampledThumbnailColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Color SampledThumbnailColor {
      get { return sampledThumbnailColor_; }
      set {
        sampledThumbnailColor_ = value;
      }
    }

    /// <summary>Field number for the "lightColorPalette" field.</summary>
    public const int LightColorPaletteFieldNumber = 13;
    private global::InnerTube.Protobuf.ColorPalette lightColorPalette_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.ColorPalette LightColorPalette {
      get { return lightColorPalette_; }
      set {
        lightColorPalette_ = value;
      }
    }

    /// <summary>Field number for the "darkColorPalette" field.</summary>
    public const int DarkColorPaletteFieldNumber = 14;
    private global::InnerTube.Protobuf.ColorPalette darkColorPalette_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.ColorPalette DarkColorPalette {
      get { return darkColorPalette_; }
      set {
        darkColorPalette_ = value;
      }
    }

    /// <summary>Field number for the "vibrantColorPalette" field.</summary>
    public const int VibrantColorPaletteFieldNumber = 18;
    private global::InnerTube.Protobuf.ColorPalette vibrantColorPalette_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.ColorPalette VibrantColorPalette {
      get { return vibrantColorPalette_; }
      set {
        vibrantColorPalette_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Thumbnails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Thumbnails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!thumbnails_.Equals(other.thumbnails_)) return false;
      if (!object.Equals(Accessibility, other.Accessibility)) return false;
      if (!object.Equals(SampledThumbnailColor, other.SampledThumbnailColor)) return false;
      if (!object.Equals(LightColorPalette, other.LightColorPalette)) return false;
      if (!object.Equals(DarkColorPalette, other.DarkColorPalette)) return false;
      if (!object.Equals(VibrantColorPalette, other.VibrantColorPalette)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= thumbnails_.GetHashCode();
      if (accessibility_ != null) hash ^= Accessibility.GetHashCode();
      if (sampledThumbnailColor_ != null) hash ^= SampledThumbnailColor.GetHashCode();
      if (lightColorPalette_ != null) hash ^= LightColorPalette.GetHashCode();
      if (darkColorPalette_ != null) hash ^= DarkColorPalette.GetHashCode();
      if (vibrantColorPalette_ != null) hash ^= VibrantColorPalette.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      thumbnails_.WriteTo(output, _repeated_thumbnails_codec);
      if (accessibility_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Accessibility);
      }
      if (sampledThumbnailColor_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(SampledThumbnailColor);
      }
      if (lightColorPalette_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DarkColorPalette);
      }
      if (vibrantColorPalette_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(VibrantColorPalette);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      thumbnails_.WriteTo(ref output, _repeated_thumbnails_codec);
      if (accessibility_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Accessibility);
      }
      if (sampledThumbnailColor_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(SampledThumbnailColor);
      }
      if (lightColorPalette_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DarkColorPalette);
      }
      if (vibrantColorPalette_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(VibrantColorPalette);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += thumbnails_.CalculateSize(_repeated_thumbnails_codec);
      if (accessibility_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Accessibility);
      }
      if (sampledThumbnailColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SampledThumbnailColor);
      }
      if (lightColorPalette_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DarkColorPalette);
      }
      if (vibrantColorPalette_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(VibrantColorPalette);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Thumbnails other) {
      if (other == null) {
        return;
      }
      thumbnails_.Add(other.thumbnails_);
      if (other.accessibility_ != null) {
        if (accessibility_ == null) {
          Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
        }
        Accessibility.MergeFrom(other.Accessibility);
      }
      if (other.sampledThumbnailColor_ != null) {
        if (sampledThumbnailColor_ == null) {
          SampledThumbnailColor = new global::InnerTube.Protobuf.Color();
        }
        SampledThumbnailColor.MergeFrom(other.SampledThumbnailColor);
      }
      if (other.lightColorPalette_ != null) {
        if (lightColorPalette_ == null) {
          LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
        }
        LightColorPalette.MergeFrom(other.LightColorPalette);
      }
      if (other.darkColorPalette_ != null) {
        if (darkColorPalette_ == null) {
          DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
        }
        DarkColorPalette.MergeFrom(other.DarkColorPalette);
      }
      if (other.vibrantColorPalette_ != null) {
        if (vibrantColorPalette_ == null) {
          VibrantColorPalette = new global::InnerTube.Protobuf.ColorPalette();
        }
        VibrantColorPalette.MergeFrom(other.VibrantColorPalette);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            thumbnails_.AddEntriesFrom(input, _repeated_thumbnails_codec);
            break;
          }
          case 34: {
            if (accessibility_ == null) {
              Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
            }
            input.ReadMessage(Accessibility);
            break;
          }
          case 98: {
            if (sampledThumbnailColor_ == null) {
              SampledThumbnailColor = new global::InnerTube.Protobuf.Color();
            }
            input.ReadMessage(SampledThumbnailColor);
            break;
          }
          case 106: {
            if (lightColorPalette_ == null) {
              LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(LightColorPalette);
            break;
          }
          case 114: {
            if (darkColorPalette_ == null) {
              DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(DarkColorPalette);
            break;
          }
          case 146: {
            if (vibrantColorPalette_ == null) {
              VibrantColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(VibrantColorPalette);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            thumbnails_.AddEntriesFrom(ref input, _repeated_thumbnails_codec);
            break;
          }
          case 34: {
            if (accessibility_ == null) {
              Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
            }
            input.ReadMessage(Accessibility);
            break;
          }
          case 98: {
            if (sampledThumbnailColor_ == null) {
              SampledThumbnailColor = new global::InnerTube.Protobuf.Color();
            }
            input.ReadMessage(SampledThumbnailColor);
            break;
          }
          case 106: {
            if (lightColorPalette_ == null) {
              LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(LightColorPalette);
            break;
          }
          case 114: {
            if (darkColorPalette_ == null) {
              DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(DarkColorPalette);
            break;
          }
          case 146: {
            if (vibrantColorPalette_ == null) {
              VibrantColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(VibrantColorPalette);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Thumbnail : pb::IMessage<Thumbnail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Thumbnail> _parser = new pb::MessageParser<Thumbnail>(() => new Thumbnail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Thumbnail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail(Thumbnail other) : this() {
      url_ = other.url_;
      width_ = other.width_;
      height_ = other.height_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail Clone() {
      return new Thumbnail(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 2;
    private int width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 3;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Thumbnail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Thumbnail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Width != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Width != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Thumbnail other) {
      if (other == null) {
        return;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Width = input.ReadInt32();
            break;
          }
          case 24: {
            Height = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Width = input.ReadInt32();
            break;
          }
          case 24: {
            Height = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Color : pb::IMessage<Color>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Color> _parser = new pb::MessageParser<Color>(() => new Color());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Color> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color(Color other) : this() {
      red_ = other.red_;
      green_ = other.green_;
      blue_ = other.blue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color Clone() {
      return new Color(this);
    }

    /// <summary>Field number for the "red" field.</summary>
    public const int RedFieldNumber = 1;
    private int red_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Red {
      get { return red_; }
      set {
        red_ = value;
      }
    }

    /// <summary>Field number for the "green" field.</summary>
    public const int GreenFieldNumber = 2;
    private int green_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Green {
      get { return green_; }
      set {
        green_ = value;
      }
    }

    /// <summary>Field number for the "blue" field.</summary>
    public const int BlueFieldNumber = 3;
    private int blue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Blue {
      get { return blue_; }
      set {
        blue_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Color);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Color other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Red != other.Red) return false;
      if (Green != other.Green) return false;
      if (Blue != other.Blue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Red != 0) hash ^= Red.GetHashCode();
      if (Green != 0) hash ^= Green.GetHashCode();
      if (Blue != 0) hash ^= Blue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Red != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Red);
      }
      if (Green != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Green);
      }
      if (Blue != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Blue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Red != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Red);
      }
      if (Green != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Green);
      }
      if (Blue != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Blue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Red != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Red);
      }
      if (Green != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Green);
      }
      if (Blue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Blue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Color other) {
      if (other == null) {
        return;
      }
      if (other.Red != 0) {
        Red = other.Red;
      }
      if (other.Green != 0) {
        Green = other.Green;
      }
      if (other.Blue != 0) {
        Blue = other.Blue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Red = input.ReadInt32();
            break;
          }
          case 16: {
            Green = input.ReadInt32();
            break;
          }
          case 24: {
            Blue = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Red = input.ReadInt32();
            break;
          }
          case 16: {
            Green = input.ReadInt32();
            break;
          }
          case 24: {
            Blue = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Icon : pb::IMessage<Icon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Icon> _parser = new pb::MessageParser<Icon>(() => new Icon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Icon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon(Icon other) : this() {
      iconType_ = other.iconType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon Clone() {
      return new Icon(this);
    }

    /// <summary>Field number for the "iconType" field.</summary>
    public const int IconTypeFieldNumber = 1;
    private int iconType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IconType {
      get { return iconType_; }
      set {
        iconType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Icon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Icon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IconType != other.IconType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IconType != 0) hash ^= IconType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IconType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IconType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IconType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IconType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IconType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IconType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Icon other) {
      if (other == null) {
        return;
      }
      if (other.IconType != 0) {
        IconType = other.IconType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IconType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IconType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccessibilityData : pb::IMessage<AccessibilityData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccessibilityData> _parser = new pb::MessageParser<AccessibilityData>(() => new AccessibilityData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccessibilityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData(AccessibilityData other) : this() {
      label_ = other.label_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData Clone() {
      return new AccessibilityData(this);
    }

    /// <summary>Field number for the "label" field.</summary>
    public const int LabelFieldNumber = 2;
    private string label_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Label {
      get { return label_; }
      set {
        label_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccessibilityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccessibilityData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Label != other.Label) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Label.Length != 0) hash ^= Label.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Label.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Label);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Label.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Label);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Label.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Label);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccessibilityData other) {
      if (other == null) {
        return;
      }
      if (other.Label.Length != 0) {
        Label = other.Label;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            Label = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            Label = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccessibilityWrapper : pb::IMessage<AccessibilityWrapper>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccessibilityWrapper> _parser = new pb::MessageParser<AccessibilityWrapper>(() => new AccessibilityWrapper());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccessibilityWrapper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper(AccessibilityWrapper other) : this() {
      accessibilityData_ = other.accessibilityData_ != null ? other.accessibilityData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper Clone() {
      return new AccessibilityWrapper(this);
    }

    /// <summary>Field number for the "accessibilityData" field.</summary>
    public const int AccessibilityDataFieldNumber = 75730170;
    private global::InnerTube.Protobuf.AccessibilityData accessibilityData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.AccessibilityData AccessibilityData {
      get { return accessibilityData_; }
      set {
        accessibilityData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccessibilityWrapper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccessibilityWrapper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccessibilityData, other.AccessibilityData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (accessibilityData_ != null) hash ^= AccessibilityData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accessibilityData_ != null) {
        output.WriteRawTag(210, 207, 241, 160, 2);
        output.WriteMessage(AccessibilityData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accessibilityData_ != null) {
        output.WriteRawTag(210, 207, 241, 160, 2);
        output.WriteMessage(AccessibilityData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (accessibilityData_ != null) {
        size += 5 + pb::CodedOutputStream.ComputeMessageSize(AccessibilityData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccessibilityWrapper other) {
      if (other == null) {
        return;
      }
      if (other.accessibilityData_ != null) {
        if (accessibilityData_ == null) {
          AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
        }
        AccessibilityData.MergeFrom(other.AccessibilityData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 605841362: {
            if (accessibilityData_ == null) {
              AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
            }
            input.ReadMessage(AccessibilityData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 605841362: {
            if (accessibilityData_ == null) {
              AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
            }
            input.ReadMessage(AccessibilityData);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ColorPalette : pb::IMessage<ColorPalette>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColorPalette> _parser = new pb::MessageParser<ColorPalette>(() => new ColorPalette());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColorPalette> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette(ColorPalette other) : this() {
      _hasBits0 = other._hasBits0;
      section1Color_ = other.section1Color_;
      section2Color_ = other.section2Color_;
      section3Color_ = other.section3Color_;
      primaryTitleColor_ = other.primaryTitleColor_;
      secondaryTitleColor_ = other.secondaryTitleColor_;
      iconInactiveColor_ = other.iconInactiveColor_;
      section4Color_ = other.section4Color_;
      iconDisabledColor_ = other.iconDisabledColor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette Clone() {
      return new ColorPalette(this);
    }

    /// <summary>Field number for the "section1Color" field.</summary>
    public const int Section1ColorFieldNumber = 1;
    private readonly static long Section1ColorDefaultValue = 0L;

    private long section1Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section1Color {
      get { if ((_hasBits0 & 1) != 0) { return section1Color_; } else { return Section1ColorDefaultValue; } }
      set {
        _hasBits0 |= 1;
        section1Color_ = value;
      }
    }
    /// <summary>Gets whether the "section1Color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSection1Color {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "section1Color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSection1Color() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "section2Color" field.</summary>
    public const int Section2ColorFieldNumber = 2;
    private readonly static long Section2ColorDefaultValue = 0L;

    private long section2Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section2Color {
      get { if ((_hasBits0 & 2) != 0) { return section2Color_; } else { return Section2ColorDefaultValue; } }
      set {
        _hasBits0 |= 2;
        section2Color_ = value;
      }
    }
    /// <summary>Gets whether the "section2Color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSection2Color {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "section2Color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSection2Color() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "section3Color" field.</summary>
    public const int Section3ColorFieldNumber = 3;
    private readonly static long Section3ColorDefaultValue = 0L;

    private long section3Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section3Color {
      get { if ((_hasBits0 & 4) != 0) { return section3Color_; } else { return Section3ColorDefaultValue; } }
      set {
        _hasBits0 |= 4;
        section3Color_ = value;
      }
    }
    /// <summary>Gets whether the "section3Color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSection3Color {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "section3Color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSection3Color() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "primaryTitleColor" field.</summary>
    public const int PrimaryTitleColorFieldNumber = 5;
    private readonly static long PrimaryTitleColorDefaultValue = 0L;

    private long primaryTitleColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PrimaryTitleColor {
      get { if ((_hasBits0 & 8) != 0) { return primaryTitleColor_; } else { return PrimaryTitleColorDefaultValue; } }
      set {
        _hasBits0 |= 8;
        primaryTitleColor_ = value;
      }
    }
    /// <summary>Gets whether the "primaryTitleColor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPrimaryTitleColor {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "primaryTitleColor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPrimaryTitleColor() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "secondaryTitleColor" field.</summary>
    public const int SecondaryTitleColorFieldNumber = 6;
    private readonly static long SecondaryTitleColorDefaultValue = 0L;

    private long secondaryTitleColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SecondaryTitleColor {
      get { if ((_hasBits0 & 16) != 0) { return secondaryTitleColor_; } else { return SecondaryTitleColorDefaultValue; } }
      set {
        _hasBits0 |= 16;
        secondaryTitleColor_ = value;
      }
    }
    /// <summary>Gets whether the "secondaryTitleColor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSecondaryTitleColor {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "secondaryTitleColor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSecondaryTitleColor() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "iconInactiveColor" field.</summary>
    public const int IconInactiveColorFieldNumber = 9;
    private readonly static long IconInactiveColorDefaultValue = 0L;

    private long iconInactiveColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IconInactiveColor {
      get { if ((_hasBits0 & 32) != 0) { return iconInactiveColor_; } else { return IconInactiveColorDefaultValue; } }
      set {
        _hasBits0 |= 32;
        iconInactiveColor_ = value;
      }
    }
    /// <summary>Gets whether the "iconInactiveColor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIconInactiveColor {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "iconInactiveColor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIconInactiveColor() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "section4Color" field.</summary>
    public const int Section4ColorFieldNumber = 10;
    private readonly static long Section4ColorDefaultValue = 0L;

    private long section4Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section4Color {
      get { if ((_hasBits0 & 64) != 0) { return section4Color_; } else { return Section4ColorDefaultValue; } }
      set {
        _hasBits0 |= 64;
        section4Color_ = value;
      }
    }
    /// <summary>Gets whether the "section4Color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSection4Color {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "section4Color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSection4Color() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "iconDisabledColor" field.</summary>
    public const int IconDisabledColorFieldNumber = 12;
    private readonly static long IconDisabledColorDefaultValue = 0L;

    private long iconDisabledColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IconDisabledColor {
      get { if ((_hasBits0 & 128) != 0) { return iconDisabledColor_; } else { return IconDisabledColorDefaultValue; } }
      set {
        _hasBits0 |= 128;
        iconDisabledColor_ = value;
      }
    }
    /// <summary>Gets whether the "iconDisabledColor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIconDisabledColor {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "iconDisabledColor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIconDisabledColor() {
      _hasBits0 &= ~128;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColorPalette);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColorPalette other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Section1Color != other.Section1Color) return false;
      if (Section2Color != other.Section2Color) return false;
      if (Section3Color != other.Section3Color) return false;
      if (PrimaryTitleColor != other.PrimaryTitleColor) return false;
      if (SecondaryTitleColor != other.SecondaryTitleColor) return false;
      if (IconInactiveColor != other.IconInactiveColor) return false;
      if (Section4Color != other.Section4Color) return false;
      if (IconDisabledColor != other.IconDisabledColor) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSection1Color) hash ^= Section1Color.GetHashCode();
      if (HasSection2Color) hash ^= Section2Color.GetHashCode();
      if (HasSection3Color) hash ^= Section3Color.GetHashCode();
      if (HasPrimaryTitleColor) hash ^= PrimaryTitleColor.GetHashCode();
      if (HasSecondaryTitleColor) hash ^= SecondaryTitleColor.GetHashCode();
      if (HasIconInactiveColor) hash ^= IconInactiveColor.GetHashCode();
      if (HasSection4Color) hash ^= Section4Color.GetHashCode();
      if (HasIconDisabledColor) hash ^= IconDisabledColor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSection1Color) {
        output.WriteRawTag(8);
        output.WriteInt64(Section1Color);
      }
      if (HasSection2Color) {
        output.WriteRawTag(16);
        output.WriteInt64(Section2Color);
      }
      if (HasSection3Color) {
        output.WriteRawTag(24);
        output.WriteInt64(Section3Color);
      }
      if (HasPrimaryTitleColor) {
        output.WriteRawTag(40);
        output.WriteInt64(PrimaryTitleColor);
      }
      if (HasSecondaryTitleColor) {
        output.WriteRawTag(48);
        output.WriteInt64(SecondaryTitleColor);
      }
      if (HasIconInactiveColor) {
        output.WriteRawTag(72);
        output.WriteInt64(IconInactiveColor);
      }
      if (HasSection4Color) {
        output.WriteRawTag(80);
        output.WriteInt64(Section4Color);
      }
      if (HasIconDisabledColor) {
        output.WriteRawTag(96);
        output.WriteInt64(IconDisabledColor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSection1Color) {
        output.WriteRawTag(8);
        output.WriteInt64(Section1Color);
      }
      if (HasSection2Color) {
        output.WriteRawTag(16);
        output.WriteInt64(Section2Color);
      }
      if (HasSection3Color) {
        output.WriteRawTag(24);
        output.WriteInt64(Section3Color);
      }
      if (HasPrimaryTitleColor) {
        output.WriteRawTag(40);
        output.WriteInt64(PrimaryTitleColor);
      }
      if (HasSecondaryTitleColor) {
        output.WriteRawTag(48);
        output.WriteInt64(SecondaryTitleColor);
      }
      if (HasIconInactiveColor) {
        output.WriteRawTag(72);
        output.WriteInt64(IconInactiveColor);
      }
      if (HasSection4Color) {
        output.WriteRawTag(80);
        output.WriteInt64(Section4Color);
      }
      if (HasIconDisabledColor) {
        output.WriteRawTag(96);
        output.WriteInt64(IconDisabledColor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSection1Color) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section1Color);
      }
      if (HasSection2Color) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section2Color);
      }
      if (HasSection3Color) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section3Color);
      }
      if (HasPrimaryTitleColor) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PrimaryTitleColor);
      }
      if (HasSecondaryTitleColor) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SecondaryTitleColor);
      }
      if (HasIconInactiveColor) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IconInactiveColor);
      }
      if (HasSection4Color) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section4Color);
      }
      if (HasIconDisabledColor) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IconDisabledColor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColorPalette other) {
      if (other == null) {
        return;
      }
      if (other.HasSection1Color) {
        Section1Color = other.Section1Color;
      }
      if (other.HasSection2Color) {
        Section2Color = other.Section2Color;
      }
      if (other.HasSection3Color) {
        Section3Color = other.Section3Color;
      }
      if (other.HasPrimaryTitleColor) {
        PrimaryTitleColor = other.PrimaryTitleColor;
      }
      if (other.HasSecondaryTitleColor) {
        SecondaryTitleColor = other.SecondaryTitleColor;
      }
      if (other.HasIconInactiveColor) {
        IconInactiveColor = other.IconInactiveColor;
      }
      if (other.HasSection4Color) {
        Section4Color = other.Section4Color;
      }
      if (other.HasIconDisabledColor) {
        IconDisabledColor = other.IconDisabledColor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Section1Color = input.ReadInt64();
            break;
          }
          case 16: {
            Section2Color = input.ReadInt64();
            break;
          }
          case 24: {
            Section3Color = input.ReadInt64();
            break;
          }
          case 40: {
            PrimaryTitleColor = input.ReadInt64();
            break;
          }
          case 48: {
            SecondaryTitleColor = input.ReadInt64();
            break;
          }
          case 72: {
            IconInactiveColor = input.ReadInt64();
            break;
          }
          case 80: {
            Section4Color = input.ReadInt64();
            break;
          }
          case 96: {
            IconDisabledColor = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Section1Color = input.ReadInt64();
            break;
          }
          case 16: {
            Section2Color = input.ReadInt64();
            break;
          }
          case 24: {
            Section3Color = input.ReadInt64();
            break;
          }
          case 40: {
            PrimaryTitleColor = input.ReadInt64();
            break;
          }
          case 48: {
            SecondaryTitleColor = input.ReadInt64();
            break;
          }
          case 72: {
            IconInactiveColor = input.ReadInt64();
            break;
          }
          case 80: {
            Section4Color = input.ReadInt64();
            break;
          }
          case 96: {
            IconDisabledColor = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
