// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: general.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InnerTube.Protobuf {

  /// <summary>Holder for reflection information generated from general.proto</summary>
  public static partial class GeneralReflection {

    #region Descriptor
    /// <summary>File descriptor for general.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneralReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1nZW5lcmFsLnByb3RvEhJJbm5lclR1YmUuUHJvdG9idWYixQIKClRodW1i",
            "bmFpbHMSMQoKdGh1bWJuYWlscxgBIAMoCzIdLklubmVyVHViZS5Qcm90b2J1",
            "Zi5UaHVtYm5haWwSRAoNYWNjZXNzaWJpbGl0eRgEIAEoCzIoLklubmVyVHVi",
            "ZS5Qcm90b2J1Zi5BY2Nlc3NpYmlsaXR5V3JhcHBlckgAiAEBEkAKEWxpZ2h0",
            "Q29sb3JQYWxldHRlGA0gASgLMiAuSW5uZXJUdWJlLlByb3RvYnVmLkNvbG9y",
            "UGFsZXR0ZUgBiAEBEj8KEGRhcmtDb2xvclBhbGV0dGUYDiABKAsyIC5Jbm5l",
            "clR1YmUuUHJvdG9idWYuQ29sb3JQYWxldHRlSAKIAQFCEAoOX2FjY2Vzc2li",
            "aWxpdHlCFAoSX2xpZ2h0Q29sb3JQYWxldHRlQhMKEV9kYXJrQ29sb3JQYWxl",
            "dHRlIjcKCVRodW1ibmFpbBILCgN1cmwYASABKAkSDQoFd2lkdGgYAiABKAUS",
            "DgoGaGVpZ2h0GAMgASgFIhgKBEljb24SEAoIaWNvblR5cGUYASABKAUiIgoR",
            "QWNjZXNzaWJpbGl0eURhdGESDQoFbGFiZWwYAiABKAkiWwoUQWNjZXNzaWJp",
            "bGl0eVdyYXBwZXISQwoRYWNjZXNzaWJpbGl0eURhdGEY+pmOJCABKAsyJS5J",
            "bm5lclR1YmUuUHJvdG9idWYuQWNjZXNzaWJpbGl0eURhdGEiogEKDENvbG9y",
            "UGFsZXR0ZRIVCg1zZWN0aW9uMUNvbG9yGAEgASgDEhUKDXNlY3Rpb24yQ29s",
            "b3IYAiABKAMSFQoNc2VjdGlvbjNDb2xvchgDIAEoAxIZChFwcmltYXJ5VGl0",
            "bGVDb2xvchgFIAEoAxIbChNzZWNvbmRhcnlUaXRsZUNvbG9yGAYgASgDEhUK",
            "DXNlY3Rpb240Q29sb3IYCiABKANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Thumbnails), global::InnerTube.Protobuf.Thumbnails.Parser, new[]{ "Thumbnails_", "Accessibility", "LightColorPalette", "DarkColorPalette" }, new[]{ "Accessibility", "LightColorPalette", "DarkColorPalette" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Thumbnail), global::InnerTube.Protobuf.Thumbnail.Parser, new[]{ "Url", "Width", "Height" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Icon), global::InnerTube.Protobuf.Icon.Parser, new[]{ "IconType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.AccessibilityData), global::InnerTube.Protobuf.AccessibilityData.Parser, new[]{ "Label" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.AccessibilityWrapper), global::InnerTube.Protobuf.AccessibilityWrapper.Parser, new[]{ "AccessibilityData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.ColorPalette), global::InnerTube.Protobuf.ColorPalette.Parser, new[]{ "Section1Color", "Section2Color", "Section3Color", "PrimaryTitleColor", "SecondaryTitleColor", "Section4Color" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Thumbnails : pb::IMessage<Thumbnails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Thumbnails> _parser = new pb::MessageParser<Thumbnails>(() => new Thumbnails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Thumbnails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails(Thumbnails other) : this() {
      thumbnails_ = other.thumbnails_.Clone();
      accessibility_ = other.accessibility_ != null ? other.accessibility_.Clone() : null;
      lightColorPalette_ = other.lightColorPalette_ != null ? other.lightColorPalette_.Clone() : null;
      darkColorPalette_ = other.darkColorPalette_ != null ? other.darkColorPalette_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnails Clone() {
      return new Thumbnails(this);
    }

    /// <summary>Field number for the "thumbnails" field.</summary>
    public const int Thumbnails_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::InnerTube.Protobuf.Thumbnail> _repeated_thumbnails_codec
        = pb::FieldCodec.ForMessage(10, global::InnerTube.Protobuf.Thumbnail.Parser);
    private readonly pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail> thumbnails_ = new pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::InnerTube.Protobuf.Thumbnail> Thumbnails_ {
      get { return thumbnails_; }
    }

    /// <summary>Field number for the "accessibility" field.</summary>
    public const int AccessibilityFieldNumber = 4;
    private global::InnerTube.Protobuf.AccessibilityWrapper accessibility_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.AccessibilityWrapper Accessibility {
      get { return accessibility_; }
      set {
        accessibility_ = value;
      }
    }

    /// <summary>Field number for the "lightColorPalette" field.</summary>
    public const int LightColorPaletteFieldNumber = 13;
    private global::InnerTube.Protobuf.ColorPalette lightColorPalette_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.ColorPalette LightColorPalette {
      get { return lightColorPalette_; }
      set {
        lightColorPalette_ = value;
      }
    }

    /// <summary>Field number for the "darkColorPalette" field.</summary>
    public const int DarkColorPaletteFieldNumber = 14;
    private global::InnerTube.Protobuf.ColorPalette darkColorPalette_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.ColorPalette DarkColorPalette {
      get { return darkColorPalette_; }
      set {
        darkColorPalette_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Thumbnails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Thumbnails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!thumbnails_.Equals(other.thumbnails_)) return false;
      if (!object.Equals(Accessibility, other.Accessibility)) return false;
      if (!object.Equals(LightColorPalette, other.LightColorPalette)) return false;
      if (!object.Equals(DarkColorPalette, other.DarkColorPalette)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= thumbnails_.GetHashCode();
      if (accessibility_ != null) hash ^= Accessibility.GetHashCode();
      if (lightColorPalette_ != null) hash ^= LightColorPalette.GetHashCode();
      if (darkColorPalette_ != null) hash ^= DarkColorPalette.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      thumbnails_.WriteTo(output, _repeated_thumbnails_codec);
      if (accessibility_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Accessibility);
      }
      if (lightColorPalette_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DarkColorPalette);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      thumbnails_.WriteTo(ref output, _repeated_thumbnails_codec);
      if (accessibility_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Accessibility);
      }
      if (lightColorPalette_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DarkColorPalette);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += thumbnails_.CalculateSize(_repeated_thumbnails_codec);
      if (accessibility_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Accessibility);
      }
      if (lightColorPalette_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LightColorPalette);
      }
      if (darkColorPalette_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DarkColorPalette);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Thumbnails other) {
      if (other == null) {
        return;
      }
      thumbnails_.Add(other.thumbnails_);
      if (other.accessibility_ != null) {
        if (accessibility_ == null) {
          Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
        }
        Accessibility.MergeFrom(other.Accessibility);
      }
      if (other.lightColorPalette_ != null) {
        if (lightColorPalette_ == null) {
          LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
        }
        LightColorPalette.MergeFrom(other.LightColorPalette);
      }
      if (other.darkColorPalette_ != null) {
        if (darkColorPalette_ == null) {
          DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
        }
        DarkColorPalette.MergeFrom(other.DarkColorPalette);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            thumbnails_.AddEntriesFrom(input, _repeated_thumbnails_codec);
            break;
          }
          case 34: {
            if (accessibility_ == null) {
              Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
            }
            input.ReadMessage(Accessibility);
            break;
          }
          case 106: {
            if (lightColorPalette_ == null) {
              LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(LightColorPalette);
            break;
          }
          case 114: {
            if (darkColorPalette_ == null) {
              DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(DarkColorPalette);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            thumbnails_.AddEntriesFrom(ref input, _repeated_thumbnails_codec);
            break;
          }
          case 34: {
            if (accessibility_ == null) {
              Accessibility = new global::InnerTube.Protobuf.AccessibilityWrapper();
            }
            input.ReadMessage(Accessibility);
            break;
          }
          case 106: {
            if (lightColorPalette_ == null) {
              LightColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(LightColorPalette);
            break;
          }
          case 114: {
            if (darkColorPalette_ == null) {
              DarkColorPalette = new global::InnerTube.Protobuf.ColorPalette();
            }
            input.ReadMessage(DarkColorPalette);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Thumbnail : pb::IMessage<Thumbnail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Thumbnail> _parser = new pb::MessageParser<Thumbnail>(() => new Thumbnail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Thumbnail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail(Thumbnail other) : this() {
      url_ = other.url_;
      width_ = other.width_;
      height_ = other.height_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Thumbnail Clone() {
      return new Thumbnail(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 2;
    private int width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 3;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Thumbnail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Thumbnail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Width != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Width != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Thumbnail other) {
      if (other == null) {
        return;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Width = input.ReadInt32();
            break;
          }
          case 24: {
            Height = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            Width = input.ReadInt32();
            break;
          }
          case 24: {
            Height = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Icon : pb::IMessage<Icon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Icon> _parser = new pb::MessageParser<Icon>(() => new Icon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Icon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon(Icon other) : this() {
      iconType_ = other.iconType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Icon Clone() {
      return new Icon(this);
    }

    /// <summary>Field number for the "iconType" field.</summary>
    public const int IconTypeFieldNumber = 1;
    private int iconType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IconType {
      get { return iconType_; }
      set {
        iconType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Icon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Icon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IconType != other.IconType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IconType != 0) hash ^= IconType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IconType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IconType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IconType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IconType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IconType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IconType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Icon other) {
      if (other == null) {
        return;
      }
      if (other.IconType != 0) {
        IconType = other.IconType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IconType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IconType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccessibilityData : pb::IMessage<AccessibilityData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccessibilityData> _parser = new pb::MessageParser<AccessibilityData>(() => new AccessibilityData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccessibilityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData(AccessibilityData other) : this() {
      label_ = other.label_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityData Clone() {
      return new AccessibilityData(this);
    }

    /// <summary>Field number for the "label" field.</summary>
    public const int LabelFieldNumber = 2;
    private string label_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Label {
      get { return label_; }
      set {
        label_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccessibilityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccessibilityData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Label != other.Label) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Label.Length != 0) hash ^= Label.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Label.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Label);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Label.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Label);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Label.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Label);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccessibilityData other) {
      if (other == null) {
        return;
      }
      if (other.Label.Length != 0) {
        Label = other.Label;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            Label = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            Label = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccessibilityWrapper : pb::IMessage<AccessibilityWrapper>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccessibilityWrapper> _parser = new pb::MessageParser<AccessibilityWrapper>(() => new AccessibilityWrapper());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccessibilityWrapper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper(AccessibilityWrapper other) : this() {
      accessibilityData_ = other.accessibilityData_ != null ? other.accessibilityData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessibilityWrapper Clone() {
      return new AccessibilityWrapper(this);
    }

    /// <summary>Field number for the "accessibilityData" field.</summary>
    public const int AccessibilityDataFieldNumber = 75730170;
    private global::InnerTube.Protobuf.AccessibilityData accessibilityData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.AccessibilityData AccessibilityData {
      get { return accessibilityData_; }
      set {
        accessibilityData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccessibilityWrapper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccessibilityWrapper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccessibilityData, other.AccessibilityData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (accessibilityData_ != null) hash ^= AccessibilityData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accessibilityData_ != null) {
        output.WriteRawTag(210, 207, 241, 160, 2);
        output.WriteMessage(AccessibilityData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accessibilityData_ != null) {
        output.WriteRawTag(210, 207, 241, 160, 2);
        output.WriteMessage(AccessibilityData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (accessibilityData_ != null) {
        size += 5 + pb::CodedOutputStream.ComputeMessageSize(AccessibilityData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccessibilityWrapper other) {
      if (other == null) {
        return;
      }
      if (other.accessibilityData_ != null) {
        if (accessibilityData_ == null) {
          AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
        }
        AccessibilityData.MergeFrom(other.AccessibilityData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 605841362: {
            if (accessibilityData_ == null) {
              AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
            }
            input.ReadMessage(AccessibilityData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 605841362: {
            if (accessibilityData_ == null) {
              AccessibilityData = new global::InnerTube.Protobuf.AccessibilityData();
            }
            input.ReadMessage(AccessibilityData);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ColorPalette : pb::IMessage<ColorPalette>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColorPalette> _parser = new pb::MessageParser<ColorPalette>(() => new ColorPalette());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColorPalette> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.GeneralReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette(ColorPalette other) : this() {
      section1Color_ = other.section1Color_;
      section2Color_ = other.section2Color_;
      section3Color_ = other.section3Color_;
      primaryTitleColor_ = other.primaryTitleColor_;
      secondaryTitleColor_ = other.secondaryTitleColor_;
      section4Color_ = other.section4Color_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorPalette Clone() {
      return new ColorPalette(this);
    }

    /// <summary>Field number for the "section1Color" field.</summary>
    public const int Section1ColorFieldNumber = 1;
    private long section1Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section1Color {
      get { return section1Color_; }
      set {
        section1Color_ = value;
      }
    }

    /// <summary>Field number for the "section2Color" field.</summary>
    public const int Section2ColorFieldNumber = 2;
    private long section2Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section2Color {
      get { return section2Color_; }
      set {
        section2Color_ = value;
      }
    }

    /// <summary>Field number for the "section3Color" field.</summary>
    public const int Section3ColorFieldNumber = 3;
    private long section3Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section3Color {
      get { return section3Color_; }
      set {
        section3Color_ = value;
      }
    }

    /// <summary>Field number for the "primaryTitleColor" field.</summary>
    public const int PrimaryTitleColorFieldNumber = 5;
    private long primaryTitleColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PrimaryTitleColor {
      get { return primaryTitleColor_; }
      set {
        primaryTitleColor_ = value;
      }
    }

    /// <summary>Field number for the "secondaryTitleColor" field.</summary>
    public const int SecondaryTitleColorFieldNumber = 6;
    private long secondaryTitleColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SecondaryTitleColor {
      get { return secondaryTitleColor_; }
      set {
        secondaryTitleColor_ = value;
      }
    }

    /// <summary>Field number for the "section4Color" field.</summary>
    public const int Section4ColorFieldNumber = 10;
    private long section4Color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Section4Color {
      get { return section4Color_; }
      set {
        section4Color_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColorPalette);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColorPalette other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Section1Color != other.Section1Color) return false;
      if (Section2Color != other.Section2Color) return false;
      if (Section3Color != other.Section3Color) return false;
      if (PrimaryTitleColor != other.PrimaryTitleColor) return false;
      if (SecondaryTitleColor != other.SecondaryTitleColor) return false;
      if (Section4Color != other.Section4Color) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Section1Color != 0L) hash ^= Section1Color.GetHashCode();
      if (Section2Color != 0L) hash ^= Section2Color.GetHashCode();
      if (Section3Color != 0L) hash ^= Section3Color.GetHashCode();
      if (PrimaryTitleColor != 0L) hash ^= PrimaryTitleColor.GetHashCode();
      if (SecondaryTitleColor != 0L) hash ^= SecondaryTitleColor.GetHashCode();
      if (Section4Color != 0L) hash ^= Section4Color.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Section1Color != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Section1Color);
      }
      if (Section2Color != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Section2Color);
      }
      if (Section3Color != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Section3Color);
      }
      if (PrimaryTitleColor != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PrimaryTitleColor);
      }
      if (SecondaryTitleColor != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SecondaryTitleColor);
      }
      if (Section4Color != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Section4Color);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Section1Color != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Section1Color);
      }
      if (Section2Color != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Section2Color);
      }
      if (Section3Color != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Section3Color);
      }
      if (PrimaryTitleColor != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PrimaryTitleColor);
      }
      if (SecondaryTitleColor != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SecondaryTitleColor);
      }
      if (Section4Color != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Section4Color);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Section1Color != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section1Color);
      }
      if (Section2Color != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section2Color);
      }
      if (Section3Color != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section3Color);
      }
      if (PrimaryTitleColor != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PrimaryTitleColor);
      }
      if (SecondaryTitleColor != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SecondaryTitleColor);
      }
      if (Section4Color != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Section4Color);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColorPalette other) {
      if (other == null) {
        return;
      }
      if (other.Section1Color != 0L) {
        Section1Color = other.Section1Color;
      }
      if (other.Section2Color != 0L) {
        Section2Color = other.Section2Color;
      }
      if (other.Section3Color != 0L) {
        Section3Color = other.Section3Color;
      }
      if (other.PrimaryTitleColor != 0L) {
        PrimaryTitleColor = other.PrimaryTitleColor;
      }
      if (other.SecondaryTitleColor != 0L) {
        SecondaryTitleColor = other.SecondaryTitleColor;
      }
      if (other.Section4Color != 0L) {
        Section4Color = other.Section4Color;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Section1Color = input.ReadInt64();
            break;
          }
          case 16: {
            Section2Color = input.ReadInt64();
            break;
          }
          case 24: {
            Section3Color = input.ReadInt64();
            break;
          }
          case 40: {
            PrimaryTitleColor = input.ReadInt64();
            break;
          }
          case 48: {
            SecondaryTitleColor = input.ReadInt64();
            break;
          }
          case 80: {
            Section4Color = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Section1Color = input.ReadInt64();
            break;
          }
          case 16: {
            Section2Color = input.ReadInt64();
            break;
          }
          case 24: {
            Section3Color = input.ReadInt64();
            break;
          }
          case 40: {
            PrimaryTitleColor = input.ReadInt64();
            break;
          }
          case 48: {
            SecondaryTitleColor = input.ReadInt64();
            break;
          }
          case 80: {
            Section4Color = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
