// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: next_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InnerTube.Protobuf.Responses {

  /// <summary>Holder for reflection information generated from next_response.proto</summary>
  public static partial class NextResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for next_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NextResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNuZXh0X3Jlc3BvbnNlLnByb3RvEhxJbm5lclR1YmUuUHJvdG9idWYuUmVz",
            "cG9uc2VzGg9yZW5kZXJlcnMucHJvdG8aDWdlbmVyYWwucHJvdG8aD2VuZHBv",
            "aW50cy5wcm90byKpAgoMTmV4dFJlc3BvbnNlEj8KCGNvbnRlbnRzGAcgASgL",
            "Mi0uSW5uZXJUdWJlLlByb3RvYnVmLlJlbmRlcmVycy5SZW5kZXJlcldyYXBw",
            "ZXISRAoUY3VycmVudFZpZGVvRW5kcG9pbnQYCSABKAsyJi5Jbm5lclR1YmUu",
            "UHJvdG9idWYuRW5kcG9pbnRzLkVuZHBvaW50EkcKEGVuZ2FnZW1lbnRQYW5l",
            "bHMYGSADKAsyLS5Jbm5lclR1YmUuUHJvdG9idWYuUmVuZGVyZXJzLlJlbmRl",
            "cmVyV3JhcHBlchJJChBmcmFtZXdvcmtVcGRhdGVzGIkGIAEoCzIuLklubmVy",
            "VHViZS5Qcm90b2J1Zi5SZXNwb25zZXMuRnJhbWV3b3JrVXBkYXRlcyJeChBG",
            "cmFtZXdvcmtVcGRhdGVzEkoKEWVudGl0eUJhdGNoVXBkYXRlGAEgASgLMi8u",
            "SW5uZXJUdWJlLlByb3RvYnVmLlJlc3BvbnNlcy5FbnRpdHlCYXRjaFVwZGF0",
            "ZSITChFFbnRpdHlCYXRjaFVwZGF0ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::InnerTube.Protobuf.Renderers.RenderersReflection.Descriptor, global::InnerTube.Protobuf.GeneralReflection.Descriptor, global::InnerTube.Protobuf.Endpoints.EndpointsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Responses.NextResponse), global::InnerTube.Protobuf.Responses.NextResponse.Parser, new[]{ "Contents", "CurrentVideoEndpoint", "EngagementPanels", "FrameworkUpdates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Responses.FrameworkUpdates), global::InnerTube.Protobuf.Responses.FrameworkUpdates.Parser, new[]{ "EntityBatchUpdate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InnerTube.Protobuf.Responses.EntityBatchUpdate), global::InnerTube.Protobuf.Responses.EntityBatchUpdate.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NextResponse : pb::IMessage<NextResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NextResponse> _parser = new pb::MessageParser<NextResponse>(() => new NextResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NextResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Responses.NextResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextResponse(NextResponse other) : this() {
      contents_ = other.contents_ != null ? other.contents_.Clone() : null;
      currentVideoEndpoint_ = other.currentVideoEndpoint_ != null ? other.currentVideoEndpoint_.Clone() : null;
      engagementPanels_ = other.engagementPanels_.Clone();
      frameworkUpdates_ = other.frameworkUpdates_ != null ? other.frameworkUpdates_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextResponse Clone() {
      return new NextResponse(this);
    }

    /// <summary>Field number for the "contents" field.</summary>
    public const int ContentsFieldNumber = 7;
    private global::InnerTube.Protobuf.Renderers.RendererWrapper contents_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Renderers.RendererWrapper Contents {
      get { return contents_; }
      set {
        contents_ = value;
      }
    }

    /// <summary>Field number for the "currentVideoEndpoint" field.</summary>
    public const int CurrentVideoEndpointFieldNumber = 9;
    private global::InnerTube.Protobuf.Endpoints.Endpoint currentVideoEndpoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Endpoints.Endpoint CurrentVideoEndpoint {
      get { return currentVideoEndpoint_; }
      set {
        currentVideoEndpoint_ = value;
      }
    }

    /// <summary>Field number for the "engagementPanels" field.</summary>
    public const int EngagementPanelsFieldNumber = 25;
    private static readonly pb::FieldCodec<global::InnerTube.Protobuf.Renderers.RendererWrapper> _repeated_engagementPanels_codec
        = pb::FieldCodec.ForMessage(202, global::InnerTube.Protobuf.Renderers.RendererWrapper.Parser);
    private readonly pbc::RepeatedField<global::InnerTube.Protobuf.Renderers.RendererWrapper> engagementPanels_ = new pbc::RepeatedField<global::InnerTube.Protobuf.Renderers.RendererWrapper>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::InnerTube.Protobuf.Renderers.RendererWrapper> EngagementPanels {
      get { return engagementPanels_; }
    }

    /// <summary>Field number for the "frameworkUpdates" field.</summary>
    public const int FrameworkUpdatesFieldNumber = 777;
    private global::InnerTube.Protobuf.Responses.FrameworkUpdates frameworkUpdates_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Responses.FrameworkUpdates FrameworkUpdates {
      get { return frameworkUpdates_; }
      set {
        frameworkUpdates_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NextResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NextResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Contents, other.Contents)) return false;
      if (!object.Equals(CurrentVideoEndpoint, other.CurrentVideoEndpoint)) return false;
      if(!engagementPanels_.Equals(other.engagementPanels_)) return false;
      if (!object.Equals(FrameworkUpdates, other.FrameworkUpdates)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (contents_ != null) hash ^= Contents.GetHashCode();
      if (currentVideoEndpoint_ != null) hash ^= CurrentVideoEndpoint.GetHashCode();
      hash ^= engagementPanels_.GetHashCode();
      if (frameworkUpdates_ != null) hash ^= FrameworkUpdates.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (contents_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Contents);
      }
      if (currentVideoEndpoint_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(CurrentVideoEndpoint);
      }
      engagementPanels_.WriteTo(output, _repeated_engagementPanels_codec);
      if (frameworkUpdates_ != null) {
        output.WriteRawTag(202, 48);
        output.WriteMessage(FrameworkUpdates);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (contents_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Contents);
      }
      if (currentVideoEndpoint_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(CurrentVideoEndpoint);
      }
      engagementPanels_.WriteTo(ref output, _repeated_engagementPanels_codec);
      if (frameworkUpdates_ != null) {
        output.WriteRawTag(202, 48);
        output.WriteMessage(FrameworkUpdates);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (contents_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contents);
      }
      if (currentVideoEndpoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentVideoEndpoint);
      }
      size += engagementPanels_.CalculateSize(_repeated_engagementPanels_codec);
      if (frameworkUpdates_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(FrameworkUpdates);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NextResponse other) {
      if (other == null) {
        return;
      }
      if (other.contents_ != null) {
        if (contents_ == null) {
          Contents = new global::InnerTube.Protobuf.Renderers.RendererWrapper();
        }
        Contents.MergeFrom(other.Contents);
      }
      if (other.currentVideoEndpoint_ != null) {
        if (currentVideoEndpoint_ == null) {
          CurrentVideoEndpoint = new global::InnerTube.Protobuf.Endpoints.Endpoint();
        }
        CurrentVideoEndpoint.MergeFrom(other.CurrentVideoEndpoint);
      }
      engagementPanels_.Add(other.engagementPanels_);
      if (other.frameworkUpdates_ != null) {
        if (frameworkUpdates_ == null) {
          FrameworkUpdates = new global::InnerTube.Protobuf.Responses.FrameworkUpdates();
        }
        FrameworkUpdates.MergeFrom(other.FrameworkUpdates);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 58: {
            if (contents_ == null) {
              Contents = new global::InnerTube.Protobuf.Renderers.RendererWrapper();
            }
            input.ReadMessage(Contents);
            break;
          }
          case 74: {
            if (currentVideoEndpoint_ == null) {
              CurrentVideoEndpoint = new global::InnerTube.Protobuf.Endpoints.Endpoint();
            }
            input.ReadMessage(CurrentVideoEndpoint);
            break;
          }
          case 202: {
            engagementPanels_.AddEntriesFrom(input, _repeated_engagementPanels_codec);
            break;
          }
          case 6218: {
            if (frameworkUpdates_ == null) {
              FrameworkUpdates = new global::InnerTube.Protobuf.Responses.FrameworkUpdates();
            }
            input.ReadMessage(FrameworkUpdates);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 58: {
            if (contents_ == null) {
              Contents = new global::InnerTube.Protobuf.Renderers.RendererWrapper();
            }
            input.ReadMessage(Contents);
            break;
          }
          case 74: {
            if (currentVideoEndpoint_ == null) {
              CurrentVideoEndpoint = new global::InnerTube.Protobuf.Endpoints.Endpoint();
            }
            input.ReadMessage(CurrentVideoEndpoint);
            break;
          }
          case 202: {
            engagementPanels_.AddEntriesFrom(ref input, _repeated_engagementPanels_codec);
            break;
          }
          case 6218: {
            if (frameworkUpdates_ == null) {
              FrameworkUpdates = new global::InnerTube.Protobuf.Responses.FrameworkUpdates();
            }
            input.ReadMessage(FrameworkUpdates);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkUpdates : pb::IMessage<FrameworkUpdates>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkUpdates> _parser = new pb::MessageParser<FrameworkUpdates>(() => new FrameworkUpdates());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkUpdates> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Responses.NextResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkUpdates() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkUpdates(FrameworkUpdates other) : this() {
      entityBatchUpdate_ = other.entityBatchUpdate_ != null ? other.entityBatchUpdate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkUpdates Clone() {
      return new FrameworkUpdates(this);
    }

    /// <summary>Field number for the "entityBatchUpdate" field.</summary>
    public const int EntityBatchUpdateFieldNumber = 1;
    private global::InnerTube.Protobuf.Responses.EntityBatchUpdate entityBatchUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InnerTube.Protobuf.Responses.EntityBatchUpdate EntityBatchUpdate {
      get { return entityBatchUpdate_; }
      set {
        entityBatchUpdate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkUpdates);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkUpdates other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EntityBatchUpdate, other.EntityBatchUpdate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (entityBatchUpdate_ != null) hash ^= EntityBatchUpdate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (entityBatchUpdate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EntityBatchUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (entityBatchUpdate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EntityBatchUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (entityBatchUpdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityBatchUpdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkUpdates other) {
      if (other == null) {
        return;
      }
      if (other.entityBatchUpdate_ != null) {
        if (entityBatchUpdate_ == null) {
          EntityBatchUpdate = new global::InnerTube.Protobuf.Responses.EntityBatchUpdate();
        }
        EntityBatchUpdate.MergeFrom(other.EntityBatchUpdate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (entityBatchUpdate_ == null) {
              EntityBatchUpdate = new global::InnerTube.Protobuf.Responses.EntityBatchUpdate();
            }
            input.ReadMessage(EntityBatchUpdate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (entityBatchUpdate_ == null) {
              EntityBatchUpdate = new global::InnerTube.Protobuf.Responses.EntityBatchUpdate();
            }
            input.ReadMessage(EntityBatchUpdate);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityBatchUpdate : pb::IMessage<EntityBatchUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityBatchUpdate> _parser = new pb::MessageParser<EntityBatchUpdate>(() => new EntityBatchUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityBatchUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InnerTube.Protobuf.Responses.NextResponseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBatchUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBatchUpdate(EntityBatchUpdate other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBatchUpdate Clone() {
      return new EntityBatchUpdate(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityBatchUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityBatchUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityBatchUpdate other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
